language: python
python:
    - "3.2"
    - "3.3"
install:
    - "pip install -r core_requirements.txt --use-mirrors"
script:
    - "nosetests"
notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.net#xbotpp"

