language: python
python:
    - "3.2"
    - "3.3"
install:
    - "make -f assist.Makefile deps"
    - "pip install ."
script:
    - "python setup.py nosetests"
notifications:
    email: false
    webhooks:
        urls:
            - http://n.tkte.ch/h/1030/iP6ytEIMOAHMpf_6WflLEbMO
