language: python
python:
    - "3.2"
    - "3.3"
install:
    - "pip install ."
script:
    - "nosetests -vw tests/xbotpp/"
notifications:
    email: false
    irc:
        channels:
            - "irc.dongcorp.org#xbotpp"
