language: python
python:
    - "3.2"
    - "3.3"
install:
    - "pip install nose irc --use-mirrors"
    - "pip install . --use-mirrors"
script:
    - "python setup.py nosetests"
notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.net#xbotpp"
            - "irc.dongcorp.org#xbotpp"
