language: python
python:
    - "3.2"
    - "3.3"
install:
    - "pip install ."
script:
    - "nosetests -vw tests/xbotpp/"
notifications:
    email: false
    webhooks:
        urls:
            - http://n.tkte.ch/h/1030/iP6ytEIMOAHMpf_6WflLEbMO
